# Generated by Django 4.1.3 on 2022-12-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_post_comment_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='post',
        ),
    ]
