# Generated by Django 3.2.6 on 2022-12-18 07:18

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_item_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailView',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.comment')),
            ],
            bases=(django.views.generic.detail.DetailView, django.contrib.auth.mixins.LoginRequiredMixin, 'shop.comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
