# Generated by Django 3.2.6 on 2022-12-18 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_auto_20221218_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
